# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
import random
# Create random tensor
A = torch.rand(size = (7,7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
B = torch.rand(size = (1,7))
#BT = torch.transpose(B)
# Perform matrix multiplication
C = torch.matmul(A,B.T)
C

tensor([[2.0743],
        [2.3706],
        [1.1115],
        [1.2823],
        [0.7935],
        [1.5296],
        [2.0883]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed

torch.manual_seed(0)
# Create two random tensors
T1 = torch.rand(size=(7,7))
T2 = torch.rand(size=(1,7))
# Matrix multiply tensors
M = torch.matmul(T1,T2.T)
M

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
# Create two random tensors on GPU
t1 = torch.rand(size = (2,3)).to(device)
t2 = torch.rand(size = (2,3)).to(device)
print(t1)
print(t2)

cuda
tensor([[0.0340, 0.9442, 0.8802],
        [0.0012, 0.5936, 0.4158]], device='cuda:0')
tensor([[0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
m_cu = torch.matmul(t1,t2.T)
m_cu

tensor([[0.8795, 1.3148],
        [0.4493, 0.7189]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_m = torch.max(m_cu)

# Find min
min_m = torch.min(m_cu)

max_m,min_m

(tensor(1.3148, device='cuda:0'), tensor(0.4493, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
index_max_m = torch.argmax(m_cu)

# Find arg min
index_min_m = torch.argmin(m_cu)

index_max_m, index_min_m

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))

In [ ]:
tensor_prac = torch.tensor([[1,2],[4,3]])
ma1 = torch.argmax(tensor_prac)
mi1 = torch.argmin(tensor_prac)
ma1,mi1

(tensor(2), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(98)

# Create random tensor

R_t = torch.rand(size = (1,1,1,10))
# Remove single dimensions
torch.manual_seed(7)
s_t = R_t.squeeze()

# Print out tensors and their shapes
print(R_t,R_t.shape)
print(s_t,s_t.shape)

tensor([[[[0.4604, 0.1011, 0.2004, 0.0959, 0.1133, 0.3090, 0.8292, 0.9408,
           0.4558, 0.9288]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4604, 0.1011, 0.2004, 0.0959, 0.1133, 0.3090, 0.8292, 0.9408, 0.4558,
        0.9288]) torch.Size([10])
